var kr_bas_23 = [];
kr_bas_23.push(new VocabClass( '일찍 이러났어요', 'I got up early'));
kr_bas_23.push(new VocabClass( '아마 오늘 밤에 도착할 거예요'));
kr_bas_23.push(new VocabClass( '매우 맛있어요', 'Very delicious'));
kr_bas_23.push(new VocabClass( '국이 약간 짜요', 'the soup is a little salty'));
kr_bas_23.push(new VocabClass( '하여튼 커피가 아주 뜨거웠어요. 그리고 비쌌어요.'));
kr_bas_23.push(new VocabClass( '가령'));
kr_bas_23.push(new VocabClass( '설령'));
kr_bas_23.push(new VocabClass( '아마', 'maybe'));
kr_bas_23.push(new VocabClass( '반드시'));
kr_bas_23.push(new VocabClass( '만일'));
kr_bas_23.push(new VocabClass( '설마'));
kr_bas_23.push(new VocabClass( '하여튼'));
kr_bas_23.push(new VocabClass( '그러나'));
kr_bas_23.push(new VocabClass( '그러니까'));
kr_bas_23.push(new VocabClass( '그러므로'));
kr_bas_23.push(new VocabClass( '그렇지만'));
kr_bas_23.push(new VocabClass( '또'));
kr_bas_23.push(new VocabClass( '또는'));
kr_bas_23.push(new VocabClass( '따라서'));
kr_bas_23.push(new VocabClass( '더군나다'));
kr_bas_23.push(new VocabClass( '그리고'));
kr_bas_23.push(new VocabClass( '그래서'));
kr_bas_23.push(new VocabClass( '그런데'));
kr_bas_23.push(new VocabClass( '그럼'));
kr_bas_23.push(new VocabClass( '또한'));
kr_bas_23.push(new VocabClass( '흑은'));
kr_bas_23.push(new VocabClass( '즉'));
kr_bas_23.push(new VocabClass( '더우기'));
kr_bas_23.push(new VocabClass( '빨리', '기사 아저씨 빨리 가 수세요'));
kr_bas_23.push(new VocabClass( '멀리'));
kr_bas_23.push(new VocabClass( '매우', '음식을 매우 맛있어요'));
kr_bas_23.push(new VocabClass( '가장', '이 가게에서 이 옷이 가장 비싸요'));
kr_bas_23.push(new VocabClass( '너무', '너무 만히 마시지 마세요'));
kr_bas_23.push(new VocabClass( '혼자서', '제니퍼가 혼자서 만들었어요'));
kr_bas_23.push(new VocabClass( '많이', '많이 사요'));
kr_bas_23.push(new VocabClass( '안녕히'));
kr_bas_23.push(new VocabClass( '천천히', '천천히 먹어요'));
kr_bas_23.push(new VocabClass( '가까이', '장문 옆에 가까이 앉으세요'));
kr_bas_23.push(new VocabClass( '제일'));
kr_bas_23.push(new VocabClass( '아주'));
kr_bas_23.push(new VocabClass( '잘', '운동을 잘 해요?'));
kr_bas_23.push(new VocabClass( '함께', '우리 함께 가세요'));
kr_bas_23.push(new VocabClass( '열심히', '열심히 공부했어요'));
kr_bas_23.push(new VocabClass( '막'));
kr_bas_23.push(new VocabClass( '벌써'));
kr_bas_23.push(new VocabClass( '아직'));
kr_bas_23.push(new VocabClass( '요즈음'));
kr_bas_23.push(new VocabClass( '현재'));
kr_bas_23.push(new VocabClass( '내일'));
kr_bas_23.push(new VocabClass( '갑자기'));
kr_bas_23.push(new VocabClass( '당분간'));
kr_bas_23.push(new VocabClass( '줄곧'));
kr_bas_23.push(new VocabClass( '마침내'));
kr_bas_23.push(new VocabClass( '언제나'));
kr_bas_23.push(new VocabClass( '늘'));
kr_bas_23.push(new VocabClass( '보통'));
kr_bas_23.push(new VocabClass( '방금'));
kr_bas_23.push(new VocabClass( '아까'));
kr_bas_23.push(new VocabClass( '이미'));
kr_bas_23.push(new VocabClass( '지금'));
kr_bas_23.push(new VocabClass( '이따'));
kr_bas_23.push(new VocabClass( '모래'));
kr_bas_23.push(new VocabClass( '냉큼'));
kr_bas_23.push(new VocabClass( '밤낮'));
kr_bas_23.push(new VocabClass( '드디어'));
kr_bas_23.push(new VocabClass( '먼저'));
kr_bas_23.push(new VocabClass( '일찍'));
kr_bas_23.push(new VocabClass( '항상'));
kr_bas_23.push(new VocabClass( '가끔'));
kr_bas_23.push(new VocabClass( '참'));
kr_bas_23.push(new VocabClass( '주로'));
kr_bas_23.push(new VocabClass( '아주'));
kr_bas_23.push(new VocabClass( '조금'));
kr_bas_23.push(new VocabClass( '너무'));
kr_bas_23.push(new VocabClass( '스티브가 항상 커피를 아주 많이 마셔요'));
kr_bas_23.push(new VocabClass( '맛있게'));
kr_bas_23.push(new VocabClass( '아름답게'));
kr_bas_23.push(new VocabClass( '점심을 맛있게 먹었어요'));
kr_bas_23.push(new VocabClass( '꽃이 아름답게 피어요.'));
kr_bas_23.push(new VocabClass( '쉽게'));
kr_bas_23.push(new VocabClass( '싸게'));
kr_bas_23.push(new VocabClass( '크게'));
kr_bas_23.push(new VocabClass( '작게'));
kr_bas_23.push(new VocabClass( '넓게'));
kr_bas_23.push(new VocabClass( '싱겁게'));
kr_bas_23.push(new VocabClass( '행복하게'));
kr_bas_23.push(new VocabClass( '간단하게'));
kr_bas_23.push(new VocabClass( '값'));
kr_bas_23.push(new VocabClass( '경치'));
kr_bas_23.push(new VocabClass( '공부하다'));
kr_bas_23.push(new VocabClass( '궁금하다'));
kr_bas_23.push(new VocabClass( '귤'));
kr_bas_23.push(new VocabClass( '길'));
kr_bas_23.push(new VocabClass( '내일'));
kr_bas_23.push(new VocabClass( '느리다'));
kr_bas_23.push(new VocabClass( '도서관'));
kr_bas_23.push(new VocabClass( '많이'));
kr_bas_23.push(new VocabClass( '맛없다'));
kr_bas_23.push(new VocabClass( '뱁다'));
kr_bas_23.push(new VocabClass( '머리'));
kr_bas_23.push(new VocabClass( '먹다'));
kr_bas_23.push(new VocabClass( '배우다'));
kr_bas_23.push(new VocabClass( '복잡하다'));
kr_bas_23.push(new VocabClass( '부드럽다'));
kr_bas_23.push(new VocabClass( '쉽다'));
kr_bas_23.push(new VocabClass( '시간'));
kr_bas_23.push(new VocabClass( '시원하다'));
kr_bas_23.push(new VocabClass( '시험'));
kr_bas_23.push(new VocabClass( '싸다'));
kr_bas_23.push(new VocabClass( '씩씩하다'));
kr_bas_23.push(new VocabClass( '아름답다'));
kr_bas_23.push(new VocabClass( '아프다'));
kr_bas_23.push(new VocabClass( '연락'));
kr_bas_23.push(new VocabClass( '오늘'));
kr_bas_23.push(new VocabClass( '외롭다'));
kr_bas_23.push(new VocabClass( '우습다'));
kr_bas_23.push(new VocabClass( '위험하다'));
kr_bas_23.push(new VocabClass( '유명하다'));
kr_bas_23.push(new VocabClass( '음식'));
kr_bas_23.push(new VocabClass( '자다'));
kr_bas_23.push(new VocabClass( '작다'));
kr_bas_23.push(new VocabClass( '전화'));
kr_bas_23.push(new VocabClass( '지하철'));
kr_bas_23.push(new VocabClass( '주다'));
kr_bas_23.push(new VocabClass( '타다'));
kr_bas_23.push(new VocabClass( '피곤하다'));
