var kr_bas_25 = [];
kr_bas_25.push(new VocabClass( '-겠', 'Similar to ㄹ 래요, 하지만 ‘겠’은 is used in formal communication, while the first one in informal. For third person it means “guess that”. In question for second person asks for opinion ‘do you think that...’'));
kr_bas_25.push(new VocabClass( '제가 내일 공항에 가겠습니다', 'I’ll go to the airport tomorrow'));
kr_bas_25.push(new VocabClass( '열심히 공부하겠습니다', 'I’ll study diligently'));
kr_bas_25.push(new VocabClass( '스테이크를 주문하겠습니다', 'I’ll order steak'));
kr_bas_25.push(new VocabClass( '내일 오후 다시 오겠습니다', 'I’ll come again tomorrow afternoon'));
kr_bas_25.push(new VocabClass( '신용 카드로 지물하시겠습니까?', 'I’ll pay with credit card'));
kr_bas_25.push(new VocabClass( '어디로 가시겠습니까?', 'Where will you go?'));
kr_bas_25.push(new VocabClass( '내일 시험이 어렵겠습니다', 'I think that tomorrow’s test will be hard'));
kr_bas_25.push(new VocabClass( '드라마가 재미있겠습니다', 'I think that the drama will be interesting'));
kr_bas_25.push(new VocabClass( '다리가 아팠겠습니다', 'I think that your legs will be hurting'));
kr_bas_25.push(new VocabClass( '학교 식당 커피가 맛있겠어요?', 'Do you think that the coffe from the school restaurant is delicious?'));
kr_bas_25.push(new VocabClass( '기름 값이 쌌겠어요?', 'Do you think that the price of oil was cheap?'));
kr_bas_25.push(new VocabClass( '오늘 밤부터 눈이 오겠습니다.', 'I’ll probably snow from today’s night'));
kr_bas_25.push(new VocabClass( '내일은 춥겠습니다', 'It’ll probably be cold tomorrow'));
kr_bas_25.push(new VocabClass( '-(으)시', 'Honor the subject of the sentence.'));
kr_bas_25.push(new VocabClass( '가다. 가세요. 사십니다.', 'Go'));
kr_bas_25.push(new VocabClass( '입다. 입으세요. 입으십니다.', 'Be'));
kr_bas_25.push(new VocabClass( '교수님, 어디에 가세요?', 'Where do you go professor?'));
kr_bas_25.push(new VocabClass( '김 교수님이 오세요.', 'professor Kim is coming'));
kr_bas_25.push(new VocabClass( '어머니는 어디에 가셔?', 'where are you going mom?'));
kr_bas_25.push(new VocabClass( '먹다. 잡수시다.', 'eat'));
kr_bas_25.push(new VocabClass( '자다. 주무시다.', 'sleep'));
kr_bas_25.push(new VocabClass( '있다. 계시다.', 'be/exist'));
kr_bas_25.push(new VocabClass( '어디에 가세요? 집에 가요.', 'Where do you go? I go home'));
kr_bas_25.push(new VocabClass( '가르치다.', 'Teach'));
kr_bas_25.push(new VocabClass( '값', 'price'));
kr_bas_25.push(new VocabClass( '서실', 'dormitory'));
kr_bas_25.push(new VocabClass( '건너다', 'to cross a road or something similar'));
kr_bas_25.push(new VocabClass( '고등학교', 'high school'));
kr_bas_25.push(new VocabClass( '공부하다', 'to study'));
kr_bas_25.push(new VocabClass( '교통', 'traffic'));
kr_bas_25.push(new VocabClass( '금요일', 'Friday'));
kr_bas_25.push(new VocabClass( '기다리다', 'to wait'));
kr_bas_25.push(new VocabClass( '길', 'road'));
kr_bas_25.push(new VocabClass( '깨끗하다', 'to be clean'));
kr_bas_25.push(new VocabClass( '꼭', 'surely, adverb'));
kr_bas_25.push(new VocabClass( '끊다', 'to quit'));
kr_bas_25.push(new VocabClass( '날씨', 'weather'));
kr_bas_25.push(new VocabClass( '내리다', 'to fall'));
kr_bas_25.push(new VocabClass( '내일', 'tomorrow'));
kr_bas_25.push(new VocabClass( '담배', 'smoke, smoking'));
kr_bas_25.push(new VocabClass( '덥다', 'To be hot, temperature'));
kr_bas_25.push(new VocabClass( '두드리다', 'To knock a door'));
kr_bas_25.push(new VocabClass( '마치다', 'To finish'));
kr_bas_25.push(new VocabClass( '막히다', 'To be stopped/held/stuck'));
kr_bas_25.push(new VocabClass( '많이', 'many (adverbial)'));
kr_bas_25.push(new VocabClass( '맛있다', 'to be delicious'));
kr_bas_25.push(new VocabClass( '매일', 'everyday'));
kr_bas_25.push(new VocabClass( '먹다', 'to eat'));
kr_bas_25.push(new VocabClass( '문', 'door'));
kr_bas_25.push(new VocabClass( '미끄럽다', 'slippery'));
kr_bas_25.push(new VocabClass( '믿다', 'to believe'));
kr_bas_25.push(new VocabClass( '바람', 'wind'));
kr_bas_25.push(new VocabClass( '방', 'room'));
kr_bas_25.push(new VocabClass( '보다', 'To see'));
kr_bas_25.push(new VocabClass( '불다', 'to blow'));
kr_bas_25.push(new VocabClass( '비', 'rain'));
kr_bas_25.push(new VocabClass( '비싸다', 'expensive'));
kr_bas_25.push(new VocabClass( '선생님', 'teacher'));
kr_bas_25.push(new VocabClass( '쉽다', 'to be easy'));
kr_bas_25.push(new VocabClass( '시험', 'exam'));
kr_bas_25.push(new VocabClass( '약속', 'promise'));
kr_bas_25.push(new VocabClass( '어렵다', 'to be difficult'));
kr_bas_25.push(new VocabClass( '에어로빅', 'aerobics'));
kr_bas_25.push(new VocabClass( '열쇠', 'keys'));
kr_bas_25.push(new VocabClass( '열심히', 'diligently'));
kr_bas_25.push(new VocabClass( '영화', 'movie'));
kr_bas_25.push(new VocabClass( '운동', 'exercise/sport'));
kr_bas_25.push(new VocabClass( '음식', 'restaurant'));
kr_bas_25.push(new VocabClass( '일', 'work'));
kr_bas_25.push(new VocabClass( '자다. 주무시다.', 'to sleep'));
kr_bas_25.push(new VocabClass( '재미있다', 'to be fun'));
kr_bas_25.push(new VocabClass( '저녁', 'dinner'));
kr_bas_25.push(new VocabClass( '전화하다', 'to call by phone'));
kr_bas_25.push(new VocabClass( '점심', 'lunch'));
kr_bas_25.push(new VocabClass( '조용하다', 'to be quiet'));
kr_bas_25.push(new VocabClass( '좁다', 'to be narrow'));
kr_bas_25.push(new VocabClass( '좋다', 'to be good'));
kr_bas_25.push(new VocabClass( '준비하다', 'to prepare'));
kr_bas_25.push(new VocabClass( '지키다', 'to keep'));
kr_bas_25.push(new VocabClass( '지하철', 'train'));
kr_bas_25.push(new VocabClass( '집', 'house'));
kr_bas_25.push(new VocabClass( '찾다', 'to find'));
kr_bas_25.push(new VocabClass( '춥다', 'to be cold'));
kr_bas_25.push(new VocabClass( '치다', 'to play'));
kr_bas_25.push(new VocabClass( '친구', 'friend'));
kr_bas_25.push(new VocabClass( '타다', 'to ride'));
kr_bas_25.push(new VocabClass( '팔다', 'to sell'));
kr_bas_25.push(new VocabClass( '품질', 'quality'));
kr_bas_25.push(new VocabClass( '하다', 'to do'));
kr_bas_25.push(new VocabClass( '흐리다', 'to be cloudy'));
kr_bas_25.push(new VocabClass( '저는 집에 가겠습니다', 'I’ll go home'));
kr_bas_25.push(new VocabClass( '제가 금요일까지 일을 마치겠습니다', 'I’ll finish the work until friday'));
kr_bas_25.push(new VocabClass( '제가 매일 운동하겠습니다', 'I’ll do exercise everyday'));
kr_bas_25.push(new VocabClass( '내일 제가 지하철을 타겠습니다', 'I’ll take the train tomorrow'));
kr_bas_25.push(new VocabClass( '제가 저녁을 준비하겠습니다', 'I’ll prepare the dinner'));
kr_bas_25.push(new VocabClass( '제가 친구를 기다니겠습니다', 'I’ll wait my friend'));
kr_bas_25.push(new VocabClass( '시험이 쉽겠습니다', 'I think the test will be easy'));
kr_bas_25.push(new VocabClass( '내일 닐씨가 춥겠습니다', 'Probably it’ll be cold tomorrow'));
kr_bas_25.push(new VocabClass( '드라마가 재미있겠습니다', 'probably the drama will be interesting'));
kr_bas_25.push(new VocabClass( '집 값이 비싸겠습니다', 'I think that the price of the house will be expensive'));
kr_bas_25.push(new VocabClass( '품질이 좋겠습니다', 'I think that the quality will be good'));
kr_bas_25.push(new VocabClass( '데니엘이 학교에 갔겠어요?', 'Do you think that daniel went to school?'));
kr_bas_25.push(new VocabClass( '담배를 끊겠습니까?', 'Will you quit smoking?'));
kr_bas_25.push(new VocabClass( '열심히 공부하겠습니까?', 'Will you study diligently?'));
kr_bas_25.push(new VocabClass( '집이 조용하겠습니까?', 'Will the house be quiet?'));
kr_bas_25.push(new VocabClass( '음식이 맛있겠습니까?', 'will the food be delicious?'));
kr_bas_25.push(new VocabClass( '방이 깨끗하겠습니까?', 'will the house be clean?'));
kr_bas_25.push(new VocabClass( '토마스가 버스를 탔겠습니까?', 'do you think that tomas took the bus?'));
kr_bas_25.push(new VocabClass( '이사밸이 전화했겠습니까?', 'Do you think that isabel called?'));
kr_bas_25.push(new VocabClass( '제시카가 친구를 기다렸겠습니까?', 'Do you think that jessica waited her friend?'));
kr_bas_25.push(new VocabClass( '매일 조깅하겠습니가.', 'I’ll do jogging everyday'));
kr_bas_25.push(new VocabClass( '매일 아에로빅을 하겠습니다.', 'I’ll do aerobics everyday'));
kr_bas_25.push(new VocabClass( '꼭 약속을 지키겠습니다.', 'surely, I’ll keep the promise'));
kr_bas_25.push(new VocabClass( '꼭 열쇠를 찾겠습니다', 'surely, I’ll find the keys'));
kr_bas_25.push(new VocabClass( '꼭 담배를 끊겠습니다.', 'surely, I’ll quit smoking'));
kr_bas_25.push(new VocabClass( '꼭 집을 팔겠습니다.', 'surely, I’ll sell the house'));
kr_bas_25.push(new VocabClass( '내일은 흐리겠습니다', 'as for tomorrow, It’ll be cloudy'));
kr_bas_25.push(new VocabClass( '내일은 비를 내리겟습니다.', 'as for tomorrow, rain will fall'));
kr_bas_25.push(new VocabClass( '내일은 많이 바람이 불겠습니다', 'as for tomorrow, many wind will blow'));
kr_bas_25.push(new VocabClass( '내일은 고통이 막히겠습니다', 'as for tomorro, the traffic will be dense'));
kr_bas_25.push(new VocabClass( '내일은 길이 미끄럽겠습니다', 'as for tomorrow the road will be slippery'));
kr_bas_25.push(new VocabClass( '집에 가십니다', 'Go home'));
kr_bas_25.push(new VocabClass( '길을 건너십니다', 'cross the road'));
kr_bas_25.push(new VocabClass( '골프를 치십니다', 'play golf'));
kr_bas_25.push(new VocabClass( '한국어를 가르치십니다', 'teach korean'));
kr_bas_25.push(new VocabClass( '문을 두드리십니다', 'know the door'));
kr_bas_25.push(new VocabClass( '한국 영화를 보십니다', 'see korean movie'));
kr_bas_25.push(new VocabClass( '그 친구를 믿으십니다', 'believe the friend'));
kr_bas_25.push(new VocabClass( '고등학교 선생님이십니다', 'be high scholl teacher'));
kr_bas_25.push(new VocabClass( '점심을 잡수십니다', 'eat dinner'));
kr_bas_25.push(new VocabClass( '거실에서 주무십니다', 'sleep at the dormitory'));
kr_bas_25.push(new VocabClass( '학교에 계십니다', 'be at school'));
