var kr_int_02 = [];
kr_int_02.push(new VocabClass( '-지요', 'This ending expresses “...right?” validation of the recipient in questions (2) implies that the recipient knows the answer. (3) in declarative way it expresses the afirmation, confirmation of something. (4) it is used to make suggestions'));
kr_int_02.push(new VocabClass( '폴이 매일 조깅을 하지요?', 'Paul does jogging everyday, right?'));
kr_int_02.push(new VocabClass( '오늘 저녁 여섯시에 만나지요?', 'Today, (we) will meet at 6pm, right?'));
kr_int_02.push(new VocabClass( '어제 학교에 왔지요?', ' (him,I,you) came to school yesterday, right?'));
kr_int_02.push(new VocabClass( '피터가 몇 시에 돌아오지요?', 'At what time does Paul return? '));
kr_int_02.push(new VocabClass( '저 사람이 누구지요?', 'Who is that person?'));
kr_int_02.push(new VocabClass( '열쇠가 어디에 있었지요?', 'Where were the keys?'));
kr_int_02.push(new VocabClass( '네, 내일 떠나지요.', '(I assure you)  Yes, (they) are leaving tomorrow'));
kr_int_02.push(new VocabClass( '영국의 수도가 런던이지요', '(I assure you) The capital of England is London'));
kr_int_02.push(new VocabClass( '테니스나 치지요', 'Shall we play tennis or something similar'));
kr_int_02.push(new VocabClass( '추운데 창문 닫지요', 'it is cold, how about closing the window'));
kr_int_02.push(new VocabClass( '점심이나 먹고 연습하지요', '(how about we) practice after eating lunch or something'));
kr_int_02.push(new VocabClass( '선생님 가시지요', 'teacher, shall we go?'));
kr_int_02.push(new VocabClass( '책 좀 피려 주시지요.', 'could you please lend me your book?'));
kr_int_02.push(new VocabClass( '-네요', 'Expresses surprise of a fact, the speaker thought the opposite '));
kr_int_02.push(new VocabClass( '종이 한국말을 잘 하네요', '(oh, I see that) john speaks Korean very well'));
kr_int_02.push(new VocabClass( '아침을 많이 준비했네요', '(Oh, I see that) (him/they/you) prepared a huge breakfast'));
kr_int_02.push(new VocabClass( '토마스가 영어 선생님이었네요', '(Oh, I see that) Tomas was an English teacher'));
kr_int_02.push(new VocabClass( '비가 많이 오네요', '(Oh, I see that) is snowing a lot'));
kr_int_02.push(new VocabClass( '이 커피가 진하네요', '(Oh, I see that) this coffee is strong'));
kr_int_02.push(new VocabClass( '-겠네요', 'expressing surprise given a thought of something'));
kr_int_02.push(new VocabClass( '음식이 많이 맵겠네요', '(Oh, I see that) the food will be very spicy'));
kr_int_02.push(new VocabClass( '내일 날씨가 춥겠네요', '(Oh, I see that) tomorrow the weather will be  cold'));
kr_int_02.push(new VocabClass( '그럼, 우리 내일 공항에서 만나겠네요', 'therefore, (Oh, I see that)  we will meet tomorrow at the airport'));
kr_int_02.push(new VocabClass( '-았/었겠네요', 'Getting surprised of , past tense'));
kr_int_02.push(new VocabClass( '만히 아팠겠네요', '(Oh, I see that) that may have been painful'));
kr_int_02.push(new VocabClass( '영화가 재미있었겠네요', '(Oh, I see that) the movie must have been interesting'));
kr_int_02.push(new VocabClass( '누나 생일이었으니까 집에  갔었겠네요', '(Oh, I see that) given that it was her sister birthday, he/she must have gone home'));
kr_int_02.push(new VocabClass( '-군요/는군요', 'Also expresses admiration, but there wasn’t an opposite expectation of the facts. For copula verb 이다/아니다 그리고 adjectives 군요 is used, otherwise 는군요 '));
kr_int_02.push(new VocabClass( '날씨가 덥군요', '(Oh, I see that) it was hot'));
kr_int_02.push(new VocabClass( '한국 음식이 맛있군요', '(Oh, I see that) korean food is delicious'));
kr_int_02.push(new VocabClass( '제시카가 일본 사람이군요', '(Oh, I see that) Jesica was Japanese'));
kr_int_02.push(new VocabClass( '여기가 존의 집이군요', '(Oh, I see that) this is John’s house'));
kr_int_02.push(new VocabClass( '일본어를 가르치는군요', '(Oh, I see that) (him) teaches Japanese'));
kr_int_02.push(new VocabClass( '매일 골프를 배우는군요', '(Oh, I see that) (you) are learning everyday golf'));
kr_int_02.push(new VocabClass( '-았/었군요'));
kr_int_02.push(new VocabClass( '영화가 재미있었군요', '(Oh, I see that) the movies was interesting'));
kr_int_02.push(new VocabClass( '한국 수도가 서울이었군요', '(Oh, I see that) Korea’s capital was Seoul'));
kr_int_02.push(new VocabClass( '-겠군요', 'Realization of a possible future'));
kr_int_02.push(new VocabClass( '서울에서 어머니를 만나겠군요', '(Oh, I see that) I’ll meet mother in Seoul'));
kr_int_02.push(new VocabClass( '내일 가게를 열겠군요', '(Oh, I see that) the shop will be open tomorrow'));
kr_int_02.push(new VocabClass( '한국 문학을 전공하겠군요', '(Oh, I see that) (she) will major in Korean literature'));
kr_int_02.push(new VocabClass( '가게', 'shop'));
kr_int_02.push(new VocabClass( '경치', 'scenery'));
kr_int_02.push(new VocabClass( '김치', 'Kimchi'));
kr_int_02.push(new VocabClass( '깨끗하다', 'to be clean'));
kr_int_02.push(new VocabClass( '날씨', 'weather'));
kr_int_02.push(new VocabClass( '닫다', 'to close'));
kr_int_02.push(new VocabClass( '덥다', 'to be hot (weather)'));
kr_int_02.push(new VocabClass( '맛있다', 'to be delicious'));
kr_int_02.push(new VocabClass( '먹다', 'to eat'));
kr_int_02.push(new VocabClass( '물가', 'price'));
kr_int_02.push(new VocabClass( '방', 'room'));
kr_int_02.push(new VocabClass( '변호사', 'lawyer'));
kr_int_02.push(new VocabClass( '비싸다', 'expensive'));
kr_int_02.push(new VocabClass( '시끄럽다', 'to be noisy'));
kr_int_02.push(new VocabClass( '신혼', 'a new marriage'));
kr_int_02.push(new VocabClass( '아름답다', 'to be pretty'));
kr_int_02.push(new VocabClass( '어제', 'yesterday'));
kr_int_02.push(new VocabClass( '없다', 'doesn’t exist'));
kr_int_02.push(new VocabClass( '여행', 'trip/travel'));
kr_int_02.push(new VocabClass( '오늘', 'today'));
kr_int_02.push(new VocabClass( '오후', 'afternoon'));
kr_int_02.push(new VocabClass( '이야기하다', 'to talk'));
kr_int_02.push(new VocabClass( '일하다', 'to work'));
kr_int_02.push(new VocabClass( '자다', 'to sleep'));
kr_int_02.push(new VocabClass( '조용하다', 'to be in silence'));
kr_int_02.push(new VocabClass( '집', 'house'));
kr_int_02.push(new VocabClass( '형', 'older brother for male'));
kr_int_02.push(new VocabClass( '닉도 오고 있지요?', 'Is nick coming? (right?)'));
kr_int_02.push(new VocabClass( '왠디가 중국 사람이지요?', 'Wendy is Chinese, right?'));
kr_int_02.push(new VocabClass( '에둬드를 만나지요?', 'Did you meet Edward, right?'));
kr_int_02.push(new VocabClass( '나를 맏지요?', 'Do you believe me?'));
kr_int_02.push(new VocabClass( '가격이 비싸지요?', 'the price is expensive ritght'));
kr_int_02.push(new VocabClass( '저기서 버스를 타지요?', 'there is where you take the bus, right?'));
kr_int_02.push(new VocabClass( '토마스가 사과를 먹고 싶어하지요?', 'Tomas likes appels right?'));
kr_int_02.push(new VocabClass( '오늘 날씨가 덥지요?', 'today’s weather is cold, right?'));
kr_int_02.push(new VocabClass( '경치가 아름답지요?', 'the scenery is beutiful, right?'));
kr_int_02.push(new VocabClass( '방이 조용하지요?', 'the room is quiet, right?'));
kr_int_02.push(new VocabClass( '집이 시끄럽지요?', 'the room is clean, right?'));
kr_int_02.push(new VocabClass( '커피가 맛있지요?', 'the coffee is delicious, right?'));
kr_int_02.push(new VocabClass( '가티 액션 영화를 보지요?', 'let’s see an action movie together?'));
kr_int_02.push(new VocabClass( '집으로 돌아가지요?', 'shall we go to the house?'));
kr_int_02.push(new VocabClass( '커피를 시키지요?', 'shall we order coffee?'));
kr_int_02.push(new VocabClass( '에어컨을 켜지요?', 'shall we start the air conditioner?'));
kr_int_02.push(new VocabClass( '린다한테 전화를 걸지요?', 'shall I call Linda?'));
kr_int_02.push(new VocabClass( '현금으로 지불하지요?', 'how about we pay by cash?'));
kr_int_02.push(new VocabClass( '생일 카드를 사지요?', 'shall we buy a birthday card?'));
kr_int_02.push(new VocabClass( '한국 영화를 빌리지요?', 'shall I borrow a korean movie?'));
kr_int_02.push(new VocabClass( '지하철을 이용하지요?', 'shall we use the subway?'));
kr_int_02.push(new VocabClass( '조디의 친구들도 초대하지요?', 'shall we invite Jody’s friends too?'));
kr_int_02.push(new VocabClass( '담배를 끊지요?', 'shall we quit smoking?'));
kr_int_02.push(new VocabClass( '밖에 비가 오네요', '(oh, I see that) it is raining outside'));
kr_int_02.push(new VocabClass( '아비게일이 노래를 잘 하네요', '(oh, I see that) Abigail sings well'));
kr_int_02.push(new VocabClass( '로날드가 부지런하네요', '(oh, I see that) Ronald is diligent'));
kr_int_02.push(new VocabClass( '디아나가 퇴근했네요', '(oh, I see that) Diana returned from work'));
kr_int_02.push(new VocabClass( '리디아가 돈을 벌었네요', '(oh, I see that) Lidia earned money'));
kr_int_02.push(new VocabClass( '반지가 비쌌네요', '(oh, I see that) the ring was expensive'));
kr_int_02.push(new VocabClass( '토마스가 제인하고 커피를 마시네요', '(oh, I see that) tomas with jein are drinking coffee'));
kr_int_02.push(new VocabClass( '조샙이 집에 없네요', '(oh, I see that) Joseph isn’t home'));
kr_int_02.push(new VocabClass( '레이첼이 깁치를 먹네요', '(oh, I see that) Rachel eats kimchi'));
kr_int_02.push(new VocabClass( '니코라스가 나탈리하고 이야기하네요', '(oh, I see that) nicolas is talking with nataly'));
kr_int_02.push(new VocabClass( '데이빗이 알엑스의 형이네요', '(oh, I see that) Daivid is alex older brother'));
kr_int_02.push(new VocabClass( '씬디가 아직 안 자네요', '(oh, I see that) Cindy hasn’t sleep yet'));
kr_int_02.push(new VocabClass( '방이 깨끗하네요', '(oh, I see that) the room is clean'));
kr_int_02.push(new VocabClass( '벌써 도착했군요', '(oh, I see that) they arrived already'));
kr_int_02.push(new VocabClass( '날씨가 싸늘하군요', '(oh, I see that) the weather is chilly'));
kr_int_02.push(new VocabClass( '보스톤이 바닷가재로 유명하군요', '(oh, I see that) Boston is famous because of the lobster'));
kr_int_02.push(new VocabClass( '어제 바람이 많이 불었군요', '(oh, I see that) yesterday has been very windy'));
kr_int_02.push(new VocabClass( '줄리아가 간호사이군요', '(oh, I see that) Julia is a nurse'));
kr_int_02.push(new VocabClass( '이제부터 여름이군요', '(oh, I see that) from now on it is summer'));
kr_int_02.push(new VocabClass( '지미 보너스를 받았군요', '(oh, I see that) Jimmy received a bonus'));
kr_int_02.push(new VocabClass( '폴이 도서관에 갔군요', '(oh, I see that) paul went to the library'));
kr_int_02.push(new VocabClass( '나오미가 패션 모델이군요', '(oh, I see that) naomy was a fashion model'));
kr_int_02.push(new VocabClass( '유럽으로 시혼 여행을 가는군요', '(oh, I see that) they went to Europe for honeymoon trip'));
kr_int_02.push(new VocabClass( '오늘 오후 9시에 가게를 닫았군요', '(oh, I see that) today at 9pm the shop was closed'));
kr_int_02.push(new VocabClass( '해리가 변호사로 일했군요', '(oh, I see that) Jery worked as a lawyer'));
kr_int_02.push(new VocabClass( '물가가 비싸군요', '(oh, I see that) the price is expensive'));
kr_int_02.push(new VocabClass( '어제 방이 더웠군요', '(oh, I see that) yesterday the room was hot'));
