var kr_int_03 = [];
kr_int_03.push(new VocabClass( '-보다', 'Used to compare to nouns'));
kr_int_03.push(new VocabClass( '제인의 방이 폴의 방보다 커요', 'Jein room is bigger than Paul’s'));
kr_int_03.push(new VocabClass( '더', 'more'));
kr_int_03.push(new VocabClass( '덜', 'less'));
kr_int_03.push(new VocabClass( '훨씬', 'far more'));
kr_int_03.push(new VocabClass( '이 옷이 그옷보다 더 비싸요', 'this clothe is more expensive than that other'));
kr_int_03.push(new VocabClass( '오늘이 어제보다 덜 추워요', 'today is less cold than yesterday'));
kr_int_03.push(new VocabClass( '제가 형보다 훨씨 더 많이 먹어요', 'I eat far more than my older brother'));
kr_int_03.push(new VocabClass( '저는 봄보다 가을을 더 좋아해요', 'I like autum more than spring'));
kr_int_03.push(new VocabClass( '앤드류가 누구보다 더 멋있어요', 'Andrew is more handsome than anyone'));
kr_int_03.push(new VocabClass( '로날드가 저보다 두 살이 더 많어요', 'Ronald is older than me by 2 years'));
kr_int_03.push(new VocabClass( '조지가 프란크보다 더 벌었어요', 'George earned more money than frank'));
kr_int_03.push(new VocabClass( '커피보다 주스를 더 마시고 싶었어요', 'I wanted to drink Juice more than coffee'));
kr_int_03.push(new VocabClass( '이 영화가 그 영화보다 덜 재미있었어요', 'This movies was less entertaining than that other'));
kr_int_03.push(new VocabClass( '톰보다 돈을 덜 쎴어요', 'I spent less money than tom'));
kr_int_03.push(new VocabClass( '브래드가 존보다 훨씨 더 유명해요', 'Andrew is more popular than John'));
kr_int_03.push(new VocabClass( '피터가 저보다 키가 더 컸었어요', 'Peter used to be taller than me'));
kr_int_03.push(new VocabClass( '-처럼 -같이', 'making comparison, “like..” “as...”'));
kr_int_03.push(new VocabClass( '앨리스가 한국 사람처럼 한국어 말을 잘 해요', 'Alice speaks Korean as good as a Korean person'));
kr_int_03.push(new VocabClass( '다이애나가 어른처럼 행동해요', 'Daiana behaves like an adult'));
kr_int_03.push(new VocabClass( '티나처럼 열심히 일하세요', 'Work diligently like Tina'));
kr_int_03.push(new VocabClass( '제인은 목소리가 남자 목소리같이 허스키해요', 'Jein’s voice is husky like a man’s'));
kr_int_03.push(new VocabClass( '어제는 여름같이 더웠어요', 'Yesterday was hot as summer'));
kr_int_03.push(new VocabClass( '오늘 밤은 낮같이 밝아요', 'Today’s night shinned like a morning'));
kr_int_03.push(new VocabClass( '-만큼', 'comparative, as much as'));
kr_int_03.push(new VocabClass( '우리 형만큼 똑똑했어요', '(i) am as inteligent as our older brother'));
kr_int_03.push(new VocabClass( '오늘은 어제만큼 덥지 않아요', 'Today wasn’t as hot as yesterday'));
kr_int_03.push(new VocabClass( '조지가 윌리엄만큼 골프를 잘 쳐요', 'George play golf as good as william'));
kr_int_03.push(new VocabClass( '이 차가 그 차만큼 비싸요', 'this car is as expensive as that another'));
kr_int_03.push(new VocabClass( '힐라리는 메리만큼 예뻐요', 'hilary isi as pretty as Monica'));
kr_int_03.push(new VocabClass( '기대', 'expectations'));
kr_int_03.push(new VocabClass( '점수', 'score'));
kr_int_03.push(new VocabClass( '나오다', 'come out, appear'));
kr_int_03.push(new VocabClass( '기대만큼 점수가 나왔어요', 'the score come out as was expected'));
kr_int_03.push(new VocabClass( '-마다', ' a counter that indicates, every'));
kr_int_03.push(new VocabClass( '부치다', 'commit, send'));
kr_int_03.push(new VocabClass( '형이 달마다 돈 부쳐 줘요', 'Older brother sends money every month'));
kr_int_03.push(new VocabClass( '넷시간마다 약을 먹으세요', 'eat the medicine every 3 hours', 'shouldn’t here be a honorif verb instead of this way'));
kr_int_03.push(new VocabClass( '방마다 텔레비션이 있어요?', 'there is a television in every room'));
kr_int_03.push(new VocabClass( '연구실', 'office, laboratory'));
kr_int_03.push(new VocabClass( '교수님마다 연구실이 있어요', 'every professor has a laboratory'));
kr_int_03.push(new VocabClass( '-마저 -조차', 'even, but used in sentences with a bad situation. Is something unfortunate'));
kr_int_03.push(new VocabClass( '토마스마저 파티에 안 왔어요', 'Even Tomas didn’t come to the party'));
kr_int_03.push(new VocabClass( '자기', 'one self'));
kr_int_03.push(new VocabClass( '그 학생은 자기 이름조차 못 써요', 'That student can’t write even his own name'));
kr_int_03.push(new VocabClass( '떠나다', 'Leave, abandon'));
kr_int_03.push(new VocabClass( '당신마저 나를 떠나면 어껗게 살아가요?', 'If you leave me, how continue living?'));
kr_int_03.push(new VocabClass( '빚', 'Debt'));
kr_int_03.push(new VocabClass( '빚때문에 집을 팔고 차마저 팔았어요', 'Because of the debt the house was sold even the car was sold'));
kr_int_03.push(new VocabClass( '굶다', 'Starve, fast'));
kr_int_03.push(new VocabClass( '아침도 굶고 점심조차 못 먹었어요', 'Couldn’t eat brekfast nor even lunch'));
kr_int_03.push(new VocabClass( '그의 여자친구마저 그의 이야기를 안 믿었어요', 'Nor even his girlfriend believes his story'));
kr_int_03.push(new VocabClass( '사고', 'Accident'));
kr_int_03.push(new VocabClass( '부인', 'Wife'));
kr_int_03.push(new VocabClass( '잃다', 'lose, pass, die'));
kr_int_03.push(new VocabClass( '차 사고로 부인하고 아들조차 잃었어요', 'Because the car accident with his wife lost even the son'));
kr_int_03.push(new VocabClass( '-밖에', 'only but, same usage as 만 but using a negative verb'));
kr_int_03.push(new VocabClass( '15 달라만 있어요. 15 덜라밖에 없어요', 'I have only 15 dollars. I have nothing but 15 dollars'));
kr_int_03.push(new VocabClass( '5 분밖에 안 기다렸어요', 'I waited only but 5 minutes'));
kr_int_03.push(new VocabClass( '차다', 'fill, full'));
kr_int_03.push(new VocabClass( '교실 반밖에 안 찼어요', 'The class was only half full'));
kr_int_03.push(new VocabClass( '잔', 'a cup'));
kr_int_03.push(new VocabClass( '커피를 두 잔밖에 안 마셨어요', 'I drank only but 2 coffee cups'));
kr_int_03.push(new VocabClass( '과목', 'Subject, course'));
kr_int_03.push(new VocabClass( '다음', 'Next'));
kr_int_03.push(new VocabClass( '학기', 'semester'));
kr_int_03.push(new VocabClass( '듣다', 'listen, attend'));
kr_int_03.push(new VocabClass( '다음 학기는 세 과목밖에 안 들을 거예요', 'I will take only but 3 courses next semester'));
kr_int_03.push(new VocabClass( '유니스는 일본어를 조금밖에 안 해요', 'Yunis speak Japanese only a little'));
kr_int_03.push(new VocabClass( '기다리다', 'to wait'));
kr_int_03.push(new VocabClass( '낮잠', 'a nap'));
kr_int_03.push(new VocabClass( '마시다', 'to drink'));
kr_int_03.push(new VocabClass( '만나다', 'to meet'));
kr_int_03.push(new VocabClass( '먹다', 'to eat'));
kr_int_03.push(new VocabClass( '분', 'minutes'));
kr_int_03.push(new VocabClass( '사과', 'apple'));
kr_int_03.push(new VocabClass( '샐러드', 'salad'));
kr_int_03.push(new VocabClass( '생각하다', 'Consider, think'));
kr_int_03.push(new VocabClass( '손님', 'customer'));
kr_int_03.push(new VocabClass( '시간', 'hour, amount of time'));
kr_int_03.push(new VocabClass( '어머니', 'mom'));
kr_int_03.push(new VocabClass( '어제', 'yesterday'));
kr_int_03.push(new VocabClass( '언니', 'older sister for female'));
kr_int_03.push(new VocabClass( '엄마', 'mom'));
kr_int_03.push(new VocabClass( '자다', 'to sleep'));
kr_int_03.push(new VocabClass( '재즈', 'jazz'));
kr_int_03.push(new VocabClass( '좋아하다', 'to like'));
kr_int_03.push(new VocabClass( '주스', 'juice'));
kr_int_03.push(new VocabClass( '주즈를 커피보다 더 마시고 싶었어요', 'I wanted to drink Juice more than coffee'));
kr_int_03.push(new VocabClass( '차르스가 리사보다 더 유행해요', 'Charles is more popular than Lisa'));
kr_int_03.push(new VocabClass( '필리핀이 한국보다 더 버워요', 'Philiphines is hotter than Korea'));
kr_int_03.push(new VocabClass( '가을을 봄보다 더 좋아했어요', 'I like autum more than spring'));
kr_int_03.push(new VocabClass( '과학', 'Science'));
kr_int_03.push(new VocabClass( '문학', 'literature'));
kr_int_03.push(new VocabClass( '전공하다', 'specialize, make a special study'));
kr_int_03.push(new VocabClass( '문학을 과학보다 더 전공하고 싶었어요', 'I wanted to specialize in literature more than science'));
kr_int_03.push(new VocabClass( '디지탈 카메라보다 노트부크를 더 사고 싶었어요?', 'Did you wanted to buy a notebook more than a digital camera?'));
kr_int_03.push(new VocabClass( '비핸기', 'plane'));
kr_int_03.push(new VocabClass( '빠르다', 'to be fast'));
kr_int_03.push(new VocabClass( '비행기가 차보다 더 빠름니다', 'A plane is faster than a car'));
kr_int_03.push(new VocabClass( '호노루루보다 뉴욕시가 더 큽니다', 'New york city is bigger than honolulu'));
kr_int_03.push(new VocabClass( '오늘이 어제보다 덜 추워요', 'today is less cold than yesterday'));
kr_int_03.push(new VocabClass( '삼이 하리보다 테니스를 더 칩니까?', 'Does sam plays more tennis than harry?'));
kr_int_03.push(new VocabClass( '재인이 대입보다 고기를 더 좋아합니까?', 'Does Jein likes meat more than David?'));
kr_int_03.push(new VocabClass( '그 아이가 하마처럼 물을 마십니다', 'That kid drinks water like an hippo'));
kr_int_03.push(new VocabClass( '얼음', 'Ice'));
kr_int_03.push(new VocabClass( '차갑다', 'To be cold, freezing'));
kr_int_03.push(new VocabClass( '주스가 얼음처럼 차갑습니다', 'The juice was cold as ice'));
kr_int_03.push(new VocabClass( '형사', 'detective'));
kr_int_03.push(new VocabClass( '행동하다', 'Dehave'));
kr_int_03.push(new VocabClass( '리디아가 형사처럼 행동합니다', 'Lidia behaves like a detective'));
kr_int_03.push(new VocabClass( '수영하다', 'to swim'));
kr_int_03.push(new VocabClass( '크리스가 물개처럼 수영을 잘 합니까?', 'Does Cris swim like a seal?'));
kr_int_03.push(new VocabClass( '양', 'the positive, a lamb'));
kr_int_03.push(new VocabClass( '순하다', 'mild, gentle'));
kr_int_03.push(new VocabClass( '제리가 양처럼 순했습니다', 'Jerry is gentle as a lamb'));
kr_int_03.push(new VocabClass( '선수', 'player'));
kr_int_03.push(new VocabClass( '농구 선수', 'basketball player'));
kr_int_03.push(new VocabClass( '존이 농수 선수처럼 키가 큽니다', 'John is tall as a basketball player'));
kr_int_03.push(new VocabClass( '날씬하다', 'to be slender, thin'));
kr_int_03.push(new VocabClass( '샌디가 모댈처럼 날씬합니다', 'Sandy is thin as a model'));
kr_int_03.push(new VocabClass( '똑똑하다', 'To be smart'));
kr_int_03.push(new VocabClass( '앤토니가 아인스타인처럼 똑똑합니다', 'Anthony is smart as Einstein'));
kr_int_03.push(new VocabClass( '오페라 가수', 'Opera singer'));
kr_int_03.push(new VocabClass( '사라가 오페라 가수처럼 노래를 잘 했습니다', 'Sara sang as an opera singer'));
kr_int_03.push(new VocabClass( '마라톤 선수', 'marathon runner'));
kr_int_03.push(new VocabClass( '뛰다', 'play, run'));
kr_int_03.push(new VocabClass( '토마스가 마라톤 선수처럼 잘 뛸 거예요', 'Tomas will run as a marathon runner'));
kr_int_03.push(new VocabClass( '부자', 'a rich person'));
kr_int_03.push(new VocabClass( '빌이 톰만큼 부자입니다', 'Bill is as rich as tom'));
kr_int_03.push(new VocabClass( '카테린이 니얼만큼 한국어를 잘 합니다', 'Katherin speaks korean as well as Neal'));
kr_int_03.push(new VocabClass( '거실', 'ones’ living room'));
kr_int_03.push(new VocabClass( '부엌', 'kitchen'));
kr_int_03.push(new VocabClass( '부엌이 거실만큼 큽니다', 'The kitchen is as big as the living room'));
kr_int_03.push(new VocabClass( '부지런하다', 'to be diligent'));
kr_int_03.push(new VocabClass( '대니엘이 필리프만큼 부지런합니다', 'Daniel is as diligent as Philiph'));
kr_int_03.push(new VocabClass( '파트리크가 에리카만큼 와인을 좋아했습니까?', 'Does patrick likes wine as much as ericka?'));
kr_int_03.push(new VocabClass( '얌전하다', 'well behaved, gentle'));
kr_int_03.push(new VocabClass( '레베카가 제니퍼만큼 얌전했습니까?', 'Is Rebecca as gentle as Jennifer?'));
kr_int_03.push(new VocabClass( '서울이 뉴욕만큼 비쌉니다', 'Seoul is as expensive as New york'));
kr_int_03.push(new VocabClass( '이 차가 그 차만큼 좋습니다', 'This car is as good as that one'));
kr_int_03.push(new VocabClass( '벌다', 'To earn money'));
kr_int_03.push(new VocabClass( '필리프가 아담만큼 돈을 벌습니다', 'Philiph earns as much money as Adam'));
kr_int_03.push(new VocabClass( '편하다', 'Comfortable, easy'));
kr_int_03.push(new VocabClass( '지하철이 택시만큼 편했습니다', 'The train is as comfortable as a taxi'));
kr_int_03.push(new VocabClass( '에드어르드가 토마스만큼 마셨습니다', 'Edward drinks as much as tomas'));
kr_int_03.push(new VocabClass( '휴가 아침마다 조깅을 합니까?', 'Does Hue do jogging every morning?'));
kr_int_03.push(new VocabClass( '저녁마다 산책합니다', 'I walk every night'));
kr_int_03.push(new VocabClass( '겨울', 'Winter'));
kr_int_03.push(new VocabClass( '겨울마다 스키를 합니까?', 'Do you sky every winter?'));
kr_int_03.push(new VocabClass( '여름', 'Summer'));
kr_int_03.push(new VocabClass( '바닷가', 'beach'));
kr_int_03.push(new VocabClass( '여름마다 바닷가에 갔습니다', 'We go to the beach every summer'));
kr_int_03.push(new VocabClass( '가게마다 바쁠 거예요', 'Every store will be busy'));
kr_int_03.push(new VocabClass( '밤마다 만납니다', 'Let’s meet every night'));
kr_int_03.push(new VocabClass( '슈퍼마케트마다 주스를 팔습니다', 'Every super market sells juice'));
kr_int_03.push(new VocabClass( '교가', 'School song'));
kr_int_03.push(new VocabClass( '학교마다 교가가 있습니다', 'Every school has a school song'));
kr_int_03.push(new VocabClass( '방마다 창문이 있었습니다', 'Every room had a window'));
kr_int_03.push(new VocabClass( '학생마다 시험으로 공부를 하고 있습니다', 'Every student is studying for the exam'));
kr_int_03.push(new VocabClass( '토요일마다 친구들 골프를 쳤습니까?', 'Do all your friends played golf every saturday?'));
kr_int_03.push(new VocabClass( '아프다', 'To be hurt'));
kr_int_03.push(new VocabClass( '제인마저 아팠습니다', 'Even Jane was hurt'));
kr_int_03.push(new VocabClass( '거짓말', 'Lies'));
kr_int_03.push(new VocabClass( '누나마저 거짓말을 했습니다', 'Even older sister told lies'));
kr_int_03.push(new VocabClass( '날씨마저 춥습니다', 'Even the weather is cold'));
kr_int_03.push(new VocabClass( '어둡다', 'to be dark'));
kr_int_03.push(new VocabClass( '제 방마저 어둡습니다. 어두워요', 'Even my room is dark'));
kr_int_03.push(new VocabClass( '고장나다', 'breakdown, trouble'));
kr_int_03.push(new VocabClass( '에어컨마저 고장났습니다', 'The air conditioner broke down'));
kr_int_03.push(new VocabClass( '마튜마저 학교에 가지 않았습니다', 'Even Matthew didn’t go to school'));
kr_int_03.push(new VocabClass( '돌아가다', 'to go back, to return'));
kr_int_03.push(new VocabClass( '부인마저 미국으로 돌아갈 거예요', 'Even my wife will return to USA'));
kr_int_03.push(new VocabClass( '떨어지다', 'to fall, to decline, to fail'));
kr_int_03.push(new VocabClass( '모니카마저 시험을 떨어졌습니다', 'Even Monica failed the test'));
kr_int_03.push(new VocabClass( '편의점', 'Convenience store'));
kr_int_03.push(new VocabClass( '편의점마저 닫았습니다', 'Even the convenience store was closed'));
kr_int_03.push(new VocabClass( '폴마저 차를 팔 것입니다', 'Even Paul will sell his car'));
kr_int_03.push(new VocabClass( '사과밖에 없어요', 'I have nothing but an apple'));
kr_int_03.push(new VocabClass( '사과 주스밖에 마시지 않아요', 'I drinnk only but apple juice'));
kr_int_03.push(new VocabClass( '샐러드밖에 안 먹어요', 'I eat only but salad'));
kr_int_03.push(new VocabClass( '엄마는 아빠밖에 못 좋아하십니다', 'Mom only likes dad'));
kr_int_03.push(new VocabClass( '손님이 일곱면밖에 없습니다', 'There are only 7 customers'));
kr_int_03.push(new VocabClass( '낮잠을 한시간밖에 안 잘 거예요', 'I will sleep only 1 hour'));
kr_int_03.push(new VocabClass( '생각하다', 'think, consider'));
kr_int_03.push(new VocabClass( '어머니밖에 못 생각했십니다', 'I think only about mom'));
kr_int_03.push(new VocabClass( '재즈밖에 좋아하지 않아요', 'I only like jazz'));
kr_int_03.push(new VocabClass( '어제 더섯시간밖에 못 잤습니다', 'yesterday I slept nothing but 5 hours'));
kr_int_03.push(new VocabClass( '십 분밖에 기다리지 않을 것입니다', 'I wait only 10 minutes'));
kr_int_03.push(new VocabClass( '언니밖에 안 만날 것입니다', 'I will meet only my older sister'));
